### ISSUE TITLE
multi module project docs path not found

### ISSUE THREAD

**Issue by SHEN-XM** [hononet639/knife4g#1]
For a multi module project, run the above command to generate the docs into a sub module. You need to copy to an external module to access it

====== no =======
demo
　├─srv1
　│ 　 └─main
　│　　　　└─**docs**
　└─srv2
　　　└─main

====== ok =======

demo
　├─srv1
　│  　└─main
　├─srv2
　│  　└─main
　└─**docs**

**Comment by hononet639** [comment]
You can try run the swag init command in the `demo` directory. The default reading is for the `./docs/swagger.json` file under the binary file.
